services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "63571:63571"
    environment:
      SERVER_PORT: "63571"
      EULA: "TRUE"
      PVP: "false"
      # TYPE: "PAPER"
      SERVER_NAME: "BeMinecraft"
      VERSION: "1.21.4"
      RCON_PASSWORD: "beuni"
      OPS: ""
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      ONLINE_MODE: "false"
      MOTD: "BeMinecraft"
      ICON: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA86ZCZHQq9nJJtM9L7YPZ4tlEFXCzVafO5A&s"
      OVERRIDE_ICON: "TRUE"
    volumes:
      - ./data:/data
      # - ./plugins:/plugins
    restart: unless-stopped
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "minecraft.logs"

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: unless-stopped
